// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module('walkin.controllers', ['geolocation']);

  app.controller('MainCtrl', [
    $scope(OpenData(geolocation(function($scope, OpenData, geolocation) {
      $scope.buildings = [];
      return OpenData.getBuildings().then(function(resp) {
        var map;
        $scope.buildings = resp.data.data;
        map = L.map('map');
        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
          attribution: '&copy; OSM'
        }).addTo(map);
        return angular.forEach($scope.buildings, function(building) {
          if (!(building.latitude && building.longitude)) {
            return;
          }
          map.setView([building.latitude, building.longitude], 18);
          return L.marker([building.latitude, building.longitude]).addTo(map).bindPopup("" + building.building_code + " (" + building.building_name + ")");
        });
      });
    })))
  ]);

}).call(this);
